import { extendTailwindMerge } from "tailwind-merge";

const twMerge = extendTailwindMerge({
  extend: {
    theme: {
      text: [
        "display-lg",
        "display-md",
        "display-sm",
        "display-xs",
        "headline-lg",
        "headline-md",
        "headline-sm",
        "headline-xs",
        "title-lg",
        "title-md",
        "title-sm",
        "title-xs",
        "label-lg",
        "label-md",
        "label-sm",
        "label-xs",
        "body-lg",
        "body-md",
        "body-sm",
        "body-xs",
      ],
      color: [
        "rosewater",
        "flamingo",
        "pink",
        "mauve",
        "red",
        "maroon",
        "peach",
        "yellow",
        "green",
        "teal",
        "sky",
        "sapphire",
        "blue",
        "lavender",
        "text",
        "subtext-1",
        "subtext-0",
        "overlay-2",
        "overlay-1",
        "overlay-0",
        "surface-2",
        "surface-1",
        "surface-0",
        "base",
        "mantle",
        "crust",
      ],
    },
  },
});

export default twMerge;
