services:
  cs12n-blog:
    container_name: cs12n-blog
    build:
      context: .
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
        NEXTAUTH_URL: ${NEXTAUTH_URL}
        NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    ports:
      - '3000:3000'
    restart: always
    command: pnpm start

  cs12n-blog-dev:
    container_name: cs12n-blog-dev
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
        NEXTAUTH_URL: ${NEXTAUTH_URL}
        NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    ports:
      - '3001:3000'
    volumes:
      - .:/app
      - /app/node_modules
    command: pnpm dev
