import '@/assets/styles/main.css';
import type { Metadata } from 'next';
import { Vazirmatn } from 'next/font/google';
import ReactAriaClientProvider from '@/components/providers/react-aria-client-provider';
import QueryProvider from '@/components/providers/query-provider';
import NextAuthProvider from '@/components/providers/session-provider';
import authOptions from '@/auth.config';
import { getServerSession } from 'next-auth';
import ReactAriaToastProvider from '@/components/providers/react-aria-toast-provider';
import { LoginModalProvider } from '@/components/providers/login-modal-provider';

type RootLayoutProps = Readonly<{ children: React.ReactNode }>;

const vazirmatn = Vazirmatn({
  display: 'swap',
  variable: '--vazirmatn',
  subsets: ['arabic', 'latin'],
});

const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

async function RootLayout(props: RootLayoutProps) {
  const { children } = props;
  const session = await getServerSession(authOptions);
  return (
    <html lang="fa" dir="rtl" className={`${vazirmatn.variable} dark`}>
      <body className={`${vazirmatn.className} antialiased`}>
        <ReactAriaClientProvider>
          <ReactAriaToastProvider />
          <NextAuthProvider session={session}>
            <QueryProvider>
              <LoginModalProvider>{children}</LoginModalProvider>
            </QueryProvider>
          </NextAuthProvider>
        </ReactAriaClientProvider>
      </body>
    </html>
  );
}

export { metadata };
export default RootLayout;
