import "~/assets/styles/main.css";
import type { Metadata } from "next";
import { Vazirmatn } from "next/font/google";
import ReactAriaClientProvider from "~/components/providers/react-aria-client-provider";

type RootLayoutProps = Readonly<{ children: React.ReactNode }>;

const vazirmatn = Vazirmatn({
  display: "swap",
  variable: "--vazirmatn",
  subsets: ["arabic", "latin"],
});

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function RootLayout(props: RootLayoutProps) {
  const { children } = props;

  return (
    <html lang="fa" dir="rtl" className={`${vazirmatn.variable} dark`}>
      <body className={`${vazirmatn.className} antialiased`}>
        <ReactAriaClientProvider>{children}</ReactAriaClientProvider>
      </body>
    </html>
  );
}

export { metadata };
export default RootLayout;
